# Generated by Django 4.2.7 on 2026-04-18 05:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_message_image_alter_message_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default platform commission % for this category (e.g., 10.00 = 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Available stock. Auto-deactivates when 0.'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('topup_request', 'Top-Up Request'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('purchase', 'Purchase (Escrow)'), ('sale', 'Sale Received'), ('commission', 'Commission Deducted'), ('refund', 'Refund')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Wallet balance after this transaction', max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Order ID or top-up request ID for reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, default='', help_text='e.g., JazzCash, EasyPaisa, Bank Transfer', max_length=200)),
                ('payment_proof', models.ImageField(blank=True, help_text='Screenshot of payment', null=True, upload_to='topup_proofs/')),
                ('transaction_id', models.CharField(blank=True, default='', help_text='External payment transaction ID', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(help_text='Snapshot of listing title at purchase', max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount held in escrow', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission % applied to this order', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Platform commission deducted', max_digits=12)),
                ('seller_amount', models.DecimalField(decimal_places=2, help_text='Amount seller receives after commission', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_note', models.TextField(blank=True, default='', help_text='Seller can include delivery details')),
                ('dispute_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.conversation')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerCommissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Custom commission % for this seller on this category', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_overrides', to='core.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Commission Override',
                'verbose_name_plural': 'Seller Commission Overrides',
                'unique_together': {('seller', 'category')},
            },
        ),
    ]
