# Generated by Django 4.2.7 on 2026-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wallet_category_commission_rate_listing_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Available stock. Leave empty for unlimited (evergreen). Auto-deactivates when finite stock reaches 0.', null=True),
        ),
    ]
