# Generated by Django 4.2.7 on 2026-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_listing_price_listing_listing_price_positive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('wallet', 'transaction_type', 'reference_id'), name='uniq_wallet_tx_type_reference'),
        ),
    ]
