# Generated by Django 5.2.13 on 2026-04-18 22:23

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wallettransaction_uniq_wallet_tx_type_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default platform commission % for this category (e.g., 10.00 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='sellercommissionoverride',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, help_text='Custom commission % for this seller on this category', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', Decimal('0.00')), ('commission_rate__lte', Decimal('100.00'))), name='category_commission_rate_0_100'),
        ),
        migrations.AddConstraint(
            model_name='sellercommissionoverride',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', Decimal('0.00')), ('commission_rate__lte', Decimal('100.00'))), name='seller_override_commission_rate_0_100'),
        ),
    ]
