# Generated by Codex on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_category_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('commission_collected', 'Commission Collected'), ('commission_reversed', 'Commission Reversed')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount. Positive credits platform revenue, negative reverses it.', max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Order ID or other external reference.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('entry_type', 'reference_id'), name='uniq_platform_ledger_type_reference'),
        ),
    ]
