# Generated by Django 5.2.13 on 2026-04-19 19:39

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_platformledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['game_category', 'status', '-created_at'], name='listing_gc_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', '-created_at'], name='listing_seller_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filter_values'], name='listing_filter_values_gin'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-id'], name='message_convo_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'sender'], name='message_unread_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='order_buyer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', '-created_at'], name='order_seller_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status'], name='order_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='platformledgerentry',
            index=models.Index(fields=['entry_type', 'reference_id'], name='platform_ledger_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='topuprequest',
            index=models.Index(fields=['user', '-created_at'], name='topup_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='topuprequest',
            index=models.Index(fields=['status', '-created_at'], name='topup_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_tx_wallet_created_idx'),
        ),
    ]
