# Generated by Django 5.2.13 on 2026-04-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='search_keywords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated search aliases (e.g., "gta, grand theft auto, gta5"). Users searching these terms will find this game.'),
        ),
    ]
