# Generated by Django 5.2.13 on 2026-04-20 00:49

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_game_search_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddConstraint(
            model_name='topuprequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('1.00'))), name='topup_amount_min_1'),
        ),
    ]
