# Generated by Django 5.2.1 on 2026-04-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery_time',
            field=models.CharField(blank=True, default='1-2 Hours', help_text='Estimated delivery time (e.g., Instant, 1-2 Hours, 24 Hours)', max_length=50),
        ),
    ]
