# Generated by Django 5.2.1 on 2026-04-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_listing_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='allow_auto_delivery',
            field=models.BooleanField(default=False, help_text='Allow sellers to create automated delivery listings in this game+category.'),
        ),
        migrations.AddField(
            model_name='listing',
            name='auto_delivery_data',
            field=models.TextField(blank=True, default='', help_text='Content delivered automatically to the buyer (e.g., account credentials, keys, codes).'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_auto_delivery',
            field=models.BooleanField(default=False, help_text='If True, delivery data is sent automatically to buyers upon purchase.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='delivery_time',
            field=models.CharField(blank=True, default='1-2 Hours', help_text='Estimated delivery time (e.g., Instant, 1-2 Hours, 24 Hours)', max_length=50),
        ),
    ]
