# Generated by Django 5.2.1 on 2026-04-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery_instructions',
            field=models.TextField(blank=True, default='', help_text='Optional instructions shown to every buyer (e.g., "Change password after receiving").'),
        ),
    ]
