# Generated by Django 5.2.1 on 2026-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delivery_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (recommended: 256x256)', null=True, upload_to='avatars/'),
        ),
    ]
