# Generated by Django 5.2.1 on 2026-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_avatar_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_changed_at',
            field=models.DateTimeField(blank=True, help_text='Last time the username was changed', null=True),
        ),
    ]
