# Generated by Django 5.2.1 on 2026-05-02 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_search_trigram_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('listing', 'Listing'), ('user', 'User')], max_length=20)),
                ('reason', models.CharField(choices=[('scam', 'Scam / Fraud'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate / Spam'), ('wrong_category', 'Wrong Category'), ('misleading', 'Misleading Information'), ('harassment', 'Harassment / Abuse'), ('stolen', 'Stolen Account / Item'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, default='', help_text='Additional details about the report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Internal admin notes on this report')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.listing')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='report_status_created_idx'), models.Index(fields=['reporter', '-created_at'], name='report_reporter_created_idx'), models.Index(fields=['target_type', 'status'], name='report_target_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('target_type', 'listing')), fields=('reporter', 'reported_listing'), name='uniq_pending_listing_report'), models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('target_type', 'user')), fields=('reporter', 'reported_user'), name='uniq_pending_user_report')],
            },
        ),
    ]
