# Generated by Django 5.2.1 on 2026-05-02 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup_request', 'Top-Up Request'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('purchase', 'Purchase (Escrow)'), ('sale', 'Sale Received'), ('commission', 'Commission Deducted'), ('refund', 'Refund'), ('withdraw_request', 'Withdraw Request'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('500.00'))])),
                ('payment_method', models.CharField(blank=True, default='', help_text='e.g., JazzCash, EasyPaisa, Bank Transfer', max_length=200)),
                ('account_details', models.CharField(blank=True, default='', help_text='Account number, IBAN, or mobile wallet number', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='withdraw_user_created_idx'), models.Index(fields=['status', '-created_at'], name='withdraw_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('500.00'))), name='withdraw_amount_min_500')],
            },
        ),
    ]
