# Generated by Django 5.2.1 on 2026-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='account_title',
            field=models.CharField(blank=True, default='', help_text='Name on the account', max_length=300),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Bank name (for bank transfers only)', max_length=300),
        ),
    ]
