# Generated by Django 5.2.1 on 2026-05-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_withdrawrequest_account_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup_request', 'Top-Up Request'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('purchase', 'Purchase'), ('sale', 'Sale Received'), ('commission', 'Commission Deducted'), ('refund', 'Refund'), ('withdraw_request', 'Withdraw Request'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected')], max_length=30),
        ),
    ]
