# Generated by Django 5.2.1 on 2026-05-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_purchase_escrow_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seller_reply',
            field=models.TextField(blank=True, default='', help_text='Optional one-time seller reply'),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_reply_at',
            field=models.DateTimeField(blank=True, help_text='When the seller replied', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
