# Generated by Django 5.2.1 on 2026-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_review_seller_reply_review_seller_reply_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Set when the buyer edits the review', null=True),
        ),
    ]
