# Generated by Django 5.2.1 on 2026-05-06 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_review_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, default='', help_text='Email for non-logged-in users', max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text='Name provided by the user', max_length=200)),
                ('category', models.CharField(choices=[('account', 'Account Issue'), ('order', 'Order Problem'), ('payment', 'Payment / Wallet'), ('seller', 'Seller Application'), ('report', 'Report / Safety'), ('feedback', 'Feedback / Suggestion'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('order_id', models.PositiveIntegerField(blank=True, help_text='Related order ID if applicable', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_reply', models.TextField(blank=True, default='', help_text='Admin response to the user')),
                ('admin_note', models.TextField(blank=True, default='', help_text='Internal admin notes (not visible to user)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for guest (non-logged-in) submissions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_ticket_status_idx'), models.Index(fields=['user', '-created_at'], name='support_ticket_user_idx')],
            },
        ),
    ]
