# Generated by Django 5.2.1 on 2026-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='admin_label',
            field=models.CharField(blank=True, default='', help_text='Internal note for admin only (e.g., "Valorant Accounts - Rank"). Not shown to users on the frontend.', max_length=300),
        ),
    ]
