# Generated by Django 5.2.14 on 2026-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Payment receipt/proof uploaded by admin after processing the withdrawal', null=True, upload_to='withdraw_receipts/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_disputed', 'Order Disputed'), ('order_cancelled', 'Order Cancelled'), ('new_review', 'New Review'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected'), ('admin_message', 'Admin Message')], max_length=30),
        ),
    ]
