# Generated by Django 5.2.14 on 2026-05-24 23:42

from django.db import migrations, models


def mark_existing_profiles_as_terms_accepted(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.update(has_accepted_terms=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_withdraw_receipt_and_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_accepted_terms',
            field=models.BooleanField(default=False, help_text='Whether the user has accepted the Terms of Service and Privacy Policy.'),
        ),
        migrations.RunPython(
            mark_existing_profiles_as_terms_accepted,
            migrations.RunPython.noop,
        ),
    ]
