# Generated by Django 5.2.14 on 2026-06-10 15:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_userprofile_email_verification_pending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup_request', 'Top-Up Request'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('jazzcash_topup', 'JazzCash Payment'), ('purchase', 'Purchase'), ('sale', 'Sale Received'), ('commission', 'Commission Deducted'), ('refund', 'Refund'), ('withdraw_request', 'Withdraw Request'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='JazzCashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('topup', 'Wallet Top-Up'), ('purchase', 'Direct Purchase')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('mobile_number', models.CharField(help_text='JazzCash mobile wallet number (e.g., 03001234567)', max_length=15)),
                ('txn_ref_no', models.CharField(help_text='pp_TxnRefNo sent to JazzCash', max_length=20, unique=True)),
                ('bill_reference', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_code', models.CharField(blank=True, default='', max_length=10)),
                ('response_message', models.CharField(blank=True, default='', max_length=500)),
                ('retrieval_reference_no', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('listing_quantity', models.PositiveIntegerField(default=1)),
                ('wallet_credited', models.BooleanField(default=False)),
                ('last_status_inquiry_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jazzcash_payments', to='core.listing')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jazzcash_payments', to='core.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jazzcash_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='jazzcash_user_created_idx'), models.Index(fields=['status', 'created_at'], name='jazzcash_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('1.00'))), name='jazzcash_amount_min_1')],
            },
        ),
    ]
