# Generated by Django 5.2.14 on 2026-06-11 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_wallettransaction_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='listing_mode',
            field=models.CharField(choices=[('standard', 'Standard (sellers list their own items)'), ('offer', 'Offers (admin-defined options, sellers compete on price)')], default='standard', help_text='Offers mode shows admin-defined options (e.g., 60 UC, 325 UC) with competing seller offers — best for top-ups and subscriptions.', max_length=20),
        ),
        migrations.CreateModel(
            name='CategoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shown to buyers (e.g., "60 UC")', max_length=200)),
                ('icon', models.ImageField(blank=True, help_text='Small icon for the option (recommended: 64x64 or 128x128)', null=True, upload_to='option_icons/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_popular', models.BooleanField(default=False, help_text='Show a "Popular" badge and preselect this option on the browse page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.gamecategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='option',
            field=models.ForeignKey(blank=True, help_text='For offers-mode categories: the option this offer is for. Title is kept in sync with the option name.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='core.categoryoption'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['option', 'status'], name='listing_option_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoryoption',
            constraint=models.UniqueConstraint(fields=('game_category', 'name'), name='category_option_gc_name_uniq'),
        ),
    ]
