# Generated by Django 5.2.14 on 2026-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_gamecategory_listing_mode_categoryoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategoryfilter',
            name='require_selection',
            field=models.BooleanField(default=False, help_text='Buyers must pick a value for this filter before offers are shown (e.g., Region for region-locked gift cards). Used by offers-mode categories.'),
        ),
    ]
