# Generated by Django 5.2.14 on 2026-06-11 09:44

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_gamecategoryfilter_require_selection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='category_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='game_name_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='game_search_keywords_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_title_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='category_name_upper_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='game_name_upper_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('search_keywords'), name='gin_trgm_ops'), name='game_keywords_upper_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='listing_title_upper_trgm_idx'),
        ),
    ]
