# Generated by Django 5.2.14 on 2026-06-11 11:04

from django.db import migrations, models


def encrypt_existing_account_fields(apps, schema_editor):
    from core.services import encrypt_sensitive_text

    WithdrawRequest = apps.get_model('core', 'WithdrawRequest')
    for withdraw in WithdrawRequest.objects.exclude(
        account_title='', account_details='',
    ).iterator():
        withdraw.account_title = encrypt_sensitive_text(withdraw.account_title)
        withdraw.account_details = encrypt_sensitive_text(withdraw.account_details)
        withdraw.save(update_fields=['account_title', 'account_details'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_category_category_name_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='account_details',
            field=models.TextField(blank=True, default='', help_text='Account number, IBAN, or mobile wallet number (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='account_title',
            field=models.TextField(blank=True, default='', help_text='Name on the account (encrypted at rest)'),
        ),
        migrations.RunPython(
            encrypt_existing_account_fields,
            migrations.RunPython.noop,
        ),
    ]
