# Generated by Django 5.2.14 on 2026-06-11 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_withdrawrequest_account_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['seller', '-created_at'], name='review_seller_created_idx'),
        ),
    ]
