# Generated by Django 5.2.14 on 2026-06-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategoryfilter',
            name='visible_when_option',
            field=models.ForeignKey(blank=True, help_text='Only show this filter after the buyer/seller picks this option on another filter in the same category (e.g., show "Region — Keys" only when Method = Digital Key). Leave empty to always show this filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_filter_assignments', to='core.filteroption'),
        ),
    ]
