# Generated by Django 5.2.14 on 2026-06-12 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_gamecategoryfilter_visible_when_options_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('system', 'System Notice'), ('delivery', 'Delivery Data'), ('instructions', 'Delivery Instructions')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_messages', to='core.order'),
        ),
        migrations.AddField(
            model_name='message',
            name='system_event',
            field=models.CharField(blank=True, choices=[('order_paid', 'Order Paid'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_disputed', 'Order Disputed'), ('order_refunded', 'Order Refunded'), ('review_posted', 'Review Posted'), ('review_updated', 'Review Updated')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
