# Generated by Django 5.2.14 on 2026-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_message_message_type_message_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional. What buyers see instead of the category name for this game (e.g., "Subscriptions" instead of "Top Ups"). Leave blank to show the category name as-is.', max_length=200),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='display_slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
