# Generated by Django 5.2.14 on 2026-06-12 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_gamecategory_display_name_gamecategory_display_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_disputed', 'Order Disputed'), ('order_cancelled', 'Order Cancelled'), ('new_review', 'New Review'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected'), ('admin_message', 'Admin Message'), ('item_request', 'Item Request')], max_length=30),
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, default='', help_text='Email for non-logged-in users', max_length=254)),
                ('message', models.TextField(help_text='What the buyer is looking for')),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', help_text='Internal admin notes (not visible to user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='core.gamecategory')),
                ('user', models.ForeignKey(blank=True, help_text='Null for guest (non-logged-in) submissions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='item_request_status_idx')],
            },
        ),
    ]
