# Generated by Django 5.2.14 on 2026-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_notification_notification_type_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='featured',
            field=models.BooleanField(default=False, help_text='Pin this game to the top of its category\'s "Popular" panel on the home page.'),
        ),
    ]
