# Generated by Django 5.2.14 on 2026-06-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_gamecategory_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='unit_name',
            field=models.CharField(blank=True, default='', help_text='Currency mode only: the unit buyers purchase in (e.g., "M" for million coins, "K" for thousand). Seller prices are PKR per 1 unit.', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Currency mode: the smallest amount (in units) a buyer can purchase per order. Always 1 for other modes.'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='listing_mode',
            field=models.CharField(choices=[('standard', 'Standard (sellers list their own items)'), ('offer', 'Offers (admin-defined options, sellers compete on price)'), ('currency', 'Currency (per-unit pricing, buyers choose an amount)')], default='standard', help_text='Offers mode shows admin-defined options (e.g., 60 UC, 325 UC) with competing seller offers — best for top-ups and subscriptions. Currency mode sells stackable in-game currency by the unit (e.g., 8 Ball Pool coins per Million) — set "Unit name" below.', max_length=20),
        ),
    ]
