# Generated by Django 5.2.14 on 2026-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_gamecategory_unit_name_listing_min_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_disputed', 'Order Disputed'), ('order_cancelled', 'Order Cancelled'), ('new_review', 'New Review'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected'), ('admin_message', 'Admin Message'), ('item_request', 'Item Request'), ('seller_approved', 'Seller Application Approved'), ('seller_rejected', 'Seller Application Rejected')], max_length=30),
        ),
    ]
