# Generated by Django 5.2.14 on 2026-07-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_seller_review_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='delivery_time',
            field=models.CharField(blank=True, default='10-15 Minutes', help_text='Estimated delivery time (e.g., Instant, 10-15 Minutes, 1-2 Hours)', max_length=50),
        ),
    ]
