# Generated by Django 5.2.14 on 2026-07-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_listing_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='jazzcashpayment',
            name='checkout_payload',
            field=models.TextField(blank=True, default='', help_text='Encrypted JSON of buyer info collected at initiation (e.g. game player ID) — forwarded to the purchase on finalize.'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_payload',
            field=models.TextField(blank=True, default='', help_text='Encrypted JSON of buyer info collected at checkout (e.g. game player ID for auto-fulfilled top-ups).'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_disputed', 'Order Disputed'), ('order_cancelled', 'Order Cancelled'), ('new_review', 'New Review'), ('topup_approved', 'Top-Up Approved'), ('topup_rejected', 'Top-Up Rejected'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected'), ('admin_message', 'Admin Message'), ('item_request', 'Item Request'), ('seller_approved', 'Seller Application Approved'), ('seller_rejected', 'Seller Application Rejected'), ('fulfillment_alert', 'Fulfillment Alert')], max_length=30),
        ),
        migrations.CreateModel(
            name='FazerProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gamekey', 'Game Key'), ('giftcard', 'Gift Card'), ('topup', 'Top-Up')], max_length=10)),
                ('fazer_category_id', models.CharField(help_text='Fazer game_id (gamekey) or category_id (giftcard/topup).', max_length=100)),
                ('offer_name', models.CharField(max_length=200)),
                ('last_sku_id', models.CharField(blank=True, default='', max_length=100)),
                ('last_cost_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Supplier cost at last sync — price-sanity baseline.', max_digits=10, null=True)),
                ('checkout_fields', models.JSONField(blank=True, default=list, help_text='Buyer info required at checkout, e.g. [{"key": "player_id", "label": "Player ID"}]. Top-ups only.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fazer_link', to='core.listing')),
            ],
        ),
        migrations.CreateModel(
            name='FazerFulfillmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gamekey', 'Game Key'), ('giftcard', 'Gift Card'), ('topup', 'Top-Up')], max_length=10)),
                ('fazer_category_id', models.CharField(max_length=100)),
                ('offer_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('placing', 'Placing'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('manual', 'Manual'), ('attention', 'Needs Attention')], default='queued', max_length=12)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('fazer_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('sub_orders', models.JSONField(blank=True, default=list, help_text='Top-up quantity>1: one Fazer order per unit [{"i": 1, "idempotency_key": ..., "fazer_order_id": ..., "status": ...}]')),
                ('charged_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('raw_response', models.TextField(blank=True, default='', help_text='Encrypted last supplier order JSON (contains codes).')),
                ('fail_reason', models.CharField(blank=True, default='', max_length=300)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fazer_task', to='core.order')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.fazerproductlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fazerproductlink',
            index=models.Index(fields=['enabled'], name='fazer_link_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='fazerfulfillmenttask',
            index=models.Index(fields=['status', 'next_poll_at'], name='fazer_task_status_poll_idx'),
        ),
        migrations.AddIndex(
            model_name='fazerfulfillmenttask',
            index=models.Index(fields=['status', 'created_at'], name='fazer_task_status_created_idx'),
        ),
    ]
