# Generated by Django 5.2.14 on 2026-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_platformsetting_jazzcashpayment_checkout_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jazzcashpayment',
            name='meta_tracking',
            field=models.TextField(blank=True, default='', help_text='JSON snapshot of browser attribution data (IP, user agent, _fbp/_fbc cookies) captured at initiation — used for the server-side Meta Purchase event when the payment resolves after the buyer left the site.'),
        ),
    ]
