# Generated by Django 5.2.14 on 2026-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_jazzcashpayment_meta_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazerfulfillmenttask',
            name='fazer_region',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='fazerproductlink',
            name='fazer_region',
            field=models.CharField(blank=True, default='', help_text="Steam gifts only: the region whose price this listing sells (PK/UA/RU/CN...). The gift is bought at this region's price and the buyer's account must match it.", max_length=8),
        ),
        migrations.AlterField(
            model_name='fazerfulfillmenttask',
            name='kind',
            field=models.CharField(choices=[('gamekey', 'Game Key'), ('giftcard', 'Gift Card'), ('topup', 'Top-Up'), ('gift', 'Steam Gift')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fazerproductlink',
            name='fazer_category_id',
            field=models.CharField(help_text='Fazer game_id (gamekey), category_id (giftcard/topup) or Steam appid (gift).', max_length=100),
        ),
        migrations.AlterField(
            model_name='fazerproductlink',
            name='kind',
            field=models.CharField(choices=[('gamekey', 'Game Key'), ('giftcard', 'Gift Card'), ('topup', 'Top-Up'), ('gift', 'Steam Gift')], max_length=10),
        ),
    ]
