# Generated by Django 5.2.14 on 2026-07-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_fazer_gift_kind_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamOfflineAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Admin-facing name, e.g. "GTA V — account 1".', max_length=200)),
                ('login', models.CharField(max_length=150)),
                ('password', models.TextField(help_text='Stored encrypted. Paste the plaintext password to change it.')),
                ('shared_secret', models.TextField(help_text='Steam Guard shared_secret (base64, from the maFile). Stored encrypted — paste plaintext to change it.')),
                ('enabled', models.BooleanField(default=True, help_text='Off: purchases fall back to manual delivery and buyers can no longer request codes.')),
                ('code_window_days', models.PositiveIntegerField(default=7, help_text='Buyers can request Steam Guard codes this many days after delivery (0 = no limit).')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='system_event',
            field=models.CharField(blank=True, choices=[('order_paid', 'Order Paid'), ('order_delivered', 'Order Delivered'), ('order_confirmed', 'Order Confirmed'), ('order_disputed', 'Order Disputed'), ('order_refunded', 'Order Refunded'), ('review_posted', 'Review Posted'), ('review_updated', 'Review Updated'), ('guard_code', 'Steam Guard Code')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='offline_account',
            field=models.ForeignKey(blank=True, help_text='Offline activation: the shared Steam account delivered to every buyer of this listing (never consumed). Enables instant delivery + on-demand Steam Guard codes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.steamofflineaccount'),
        ),
    ]
