# Generated by Django 5.2.14 on 2026-07-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_steamofflineaccount_alter_message_system_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamofflineaccount',
            name='guard_type',
            field=models.CharField(choices=[('totp', 'Mobile authenticator (shared_secret)'), ('email', 'Email Steam Guard (shared mailbox)')], default='totp', help_text="email: the account's contact email must point at the shared guard mailbox (GUARD_EMAIL_IMAP_* env vars).", max_length=8),
        ),
        migrations.AlterField(
            model_name='steamofflineaccount',
            name='shared_secret',
            field=models.TextField(blank=True, default='', help_text='Mobile-authenticator type only: the Steam Guard shared_secret (base64, from the maFile). Stored encrypted — paste plaintext to change it.'),
        ),
    ]
