# Generated by Django 5.2.14 on 2026-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_steamofflineaccount_guard_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guard_code_issued_at',
            field=models.DateTimeField(blank=True, help_text='Offline activation: when the buyer was given their one Steam Guard code. Set once — further requests are refused.', null=True),
        ),
    ]
