# Generated by Django 5.2.14 on 2026-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_offlineaccount_guard_email_offlineaccount_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='seo_body',
            field=models.TextField(blank=True, default='', help_text='Visible SEO text rendered below the listings on the category page. Separate paragraphs with a blank line; lines starting with "## " become subheadings. Blank = no text block.'),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Custom meta description shown under the title in Google. Aim for 140-160 characters. Blank = auto-generated.', max_length=300),
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Custom search/browser title for this page, WITHOUT the "| GamesBazaar" suffix (the site adds it). Aim for ~50 characters. Blank = auto-generated from the game and category names.', max_length=120),
        ),
    ]
