# Generated by Django 5.2.14 on 2026-07-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_gamecategory_seo_body_gamecategory_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='offline_account',
            field=models.ForeignKey(blank=True, help_text='Offline activation: the shared game account (Steam/Ubisoft/EA/Epic) delivered to every buyer of this listing (never consumed). Enables instant delivery + on-demand login codes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.offlineaccount'),
        ),
        migrations.AlterField(
            model_name='offlineaccount',
            name='guard_email',
            field=models.CharField(blank=True, default='', help_text='Ubisoft/EA/Epic only: the email address this account is registered under. Must deliver into the shared guard mailbox (Gmail dot/plus alias of it, or auto-forwarded) — codes are matched by this To: address. Steam accounts leave it blank (matched by login in the email body).', max_length=254),
        ),
        migrations.AlterField(
            model_name='offlineaccount',
            name='guard_type',
            field=models.CharField(choices=[('totp', 'Mobile authenticator (shared_secret)'), ('email', 'Email code (shared mailbox)')], default='totp', help_text='email: code emails for this account must land in the shared guard mailbox (GUARD_EMAIL_IMAP_* env vars). Ubisoft/EA/Epic accounts are always email.', max_length=8),
        ),
        migrations.AlterField(
            model_name='offlineaccount',
            name='platform',
            field=models.CharField(choices=[('steam', 'Steam'), ('ubisoft', 'Ubisoft'), ('ea', 'EA'), ('epic', 'Epic Games')], default='steam', max_length=10),
        ),
    ]
