# Generated by Django 5.2.14 on 2026-07-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_listing_offline_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineaccount',
            name='mailbox_host',
            field=models.CharField(blank=True, default='', help_text='Only for accounts whose registered mailbox cannot forward (e.g. Rambler): its IMAP server, e.g. imap.rambler.ru — codes are then fetched from that mailbox directly (SSL, port 993) instead of the shared guard mailbox. Enable IMAP/mail-client access in the provider settings first. Leave blank to use the shared mailbox.', max_length=254),
        ),
        migrations.AddField(
            model_name='offlineaccount',
            name='mailbox_password',
            field=models.TextField(blank=True, default='', help_text='Own mailbox only: stored encrypted. Paste the plaintext mailbox password to change it.'),
        ),
        migrations.AddField(
            model_name='offlineaccount',
            name='mailbox_user',
            field=models.CharField(blank=True, default='', help_text='Own mailbox only: its login, usually the full address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='offlineaccount',
            name='guard_email',
            field=models.CharField(blank=True, default='', help_text="Ubisoft/EA/Epic only: the email address this account is registered under. Must deliver into the shared guard mailbox (Gmail dot/plus alias of it, or auto-forwarded) — codes are matched by this To: address. Steam accounts leave it blank (matched by login in the email body). Own-mailbox accounts: the mailbox's own address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='offlineaccount',
            name='guard_type',
            field=models.CharField(choices=[('totp', 'Mobile authenticator (shared_secret)'), ('email', 'Email code (shared mailbox)')], default='totp', help_text='email: code emails for this account must land in the shared guard mailbox (GUARD_EMAIL_IMAP_* env vars) — or its own mailbox, when the mailbox fields below are set. Ubisoft/EA/Epic accounts are always email.', max_length=8),
        ),
    ]
