# Generated by Django 5.2.14 on 2026-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_offlineaccount_mailbox_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_official_store',
            field=models.BooleanField(default=False, help_text='Show the "Official Store" check mark next to this seller\'s name everywhere buyers see it. Reserve it for in-house shops — it only means something while few sellers carry it.'),
        ),
    ]
