# Generated by Django 5.2.14 on 2026-08-22 12:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_userprofile_is_official_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat checkout service fee the buyer paid on top of total_amount. Platform revenue; returned on refund.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('commission_collected', 'Commission Collected'), ('commission_reversed', 'Commission Reversed'), ('service_fee_collected', 'Service Fee Collected'), ('service_fee_reversed', 'Service Fee Reversed')], max_length=40),
        ),
    ]
