# Generated by Django 5.2.14 on 2026-08-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_order_service_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('listing_title', models.CharField(blank=True, default='', help_text='Snapshot of listing title at click time', max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Expected total at click time — correct it to what the buyer actually paid before marking the row completed.', max_digits=12, null=True)),
                ('page_url', models.CharField(blank=True, default='', help_text='Page the click came from', max_length=500)),
                ('meta_tracking', models.TextField(blank=True, default='', help_text='JSON snapshot of browser attribution data (IP, user agent, _fbp/_fbc cookies) captured at click time — replayed into the Meta Purchase event when the sale is recorded.')),
                ('buyer_phone', models.CharField(blank=True, default='', help_text="Buyer's WhatsApp number (e.g. 03001234567) — required to mark the sale completed.", max_length=20)),
                ('status', models.CharField(choices=[('clicked', 'Clicked'), ('completed', 'Completed')], default='clicked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_checkouts', to='core.listing')),
                ('user', models.ForeignKey(blank=True, help_text='Set when the clicker was logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wa_checkout_status_idx')],
            },
        ),
    ]
