# Generated by Django 5.2.14 on 2026-08-22 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_reviewimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='whatsapp_checkout',
            field=models.OneToOneField(blank=True, help_text='Set instead of order when the sale closed on WhatsApp.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.whatsappcheckout'),
        ),
        migrations.AddField(
            model_name='whatsappcheckout',
            name='review_token',
            field=models.CharField(blank=True, editable=False, help_text='One-time review link token, minted when the sale is marked completed. The link is pasted into the WhatsApp chat so the buyer can review without an account.', max_length=48, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Empty for WhatsApp-sale reviews — the buyer has no account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('whatsapp_checkout__isnull', True)), models.Q(('order__isnull', True), ('whatsapp_checkout__isnull', False)), _connector='OR'), name='review_exactly_one_source'),
        ),
    ]
