# Generated by Django 5.2.14 on 2026-08-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_backfill_whatsapp_review_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_source',
            field=models.CharField(blank=True, default='', help_text="Snapshot of the buyer's first-touch acquisition source at purchase time (blank for pre-attribution accounts).", max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acquisition_first_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the browser first saw the site. Also the write-once flag: set means attribution was captured.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acquisition_landing_page',
            field=models.CharField(blank=True, default='', help_text='Path + query the first visit landed on (UTM tags live here).', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acquisition_referrer',
            field=models.CharField(blank=True, default='', help_text='Raw document.referrer of the first visit.', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acquisition_source',
            field=models.CharField(blank=True, default='', help_text="Derived source label for the user's first visit (google, chatgpt, facebook, direct, ...).", max_length=32),
        ),
    ]
