# Generated by Django 5.2.14 on 2026-08-26 15:44
#
# Sold counts + review-request emails. sales_count is the denormalized
# "N sold" number on listing cards (completed on-site orders + completed
# WhatsApp sales); completed_at anchors the review-email delay and is
# backfilled from delivered_at (orders complete on delivery since the
# 2026-08 shop conversion), falling back to updated_at for the few
# completed orders that never stamped delivered_at (dispute releases).

from django.db import migrations, models
from django.db.models import Count, F


def backfill_completed_at(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    Order.objects.filter(
        status='completed', delivered_at__isnull=False,
    ).update(completed_at=F('delivered_at'))
    Order.objects.filter(
        status='completed', completed_at__isnull=True,
    ).update(completed_at=F('updated_at'))


def backfill_sales_counts(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    WhatsAppCheckout = apps.get_model('core', 'WhatsAppCheckout')
    Listing = apps.get_model('core', 'Listing')

    counts = {}
    for row in (
        Order.objects.filter(status='completed', listing__isnull=False)
        .values('listing_id').annotate(n=Count('id'))
    ):
        counts[row['listing_id']] = counts.get(row['listing_id'], 0) + row['n']
    for row in (
        WhatsAppCheckout.objects.filter(status='completed', listing__isnull=False)
        .values('listing_id').annotate(n=Count('id'))
    ):
        counts[row['listing_id']] = counts.get(row['listing_id'], 0) + row['n']

    for listing_id, n in counts.items():
        Listing.objects.filter(pk=listing_id).update(sales_count=n)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_order_buyer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, help_text='Completed sales of this listing — on-site orders plus WhatsApp sales. Denormalized: bumped on completion, dropped on refund; shown on cards as "N sold".'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the order entered completed status.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the review-request email was queued. Stamped in the same transaction so the timer never emails a buyer twice.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_token',
            field=models.CharField(blank=True, editable=False, help_text='No-login review-link token, minted when the review-request email goes out. Serves the same /review/<token> page as WhatsApp sales.', max_length=48, null=True, unique=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
        migrations.RunPython(backfill_sales_counts, migrations.RunPython.noop),
    ]
