# Generated by Django 5.2.14 on 2026-09-02 06:12

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_listing_sales_count_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoption',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small icon for the option (recommended: 64x64 or 128x128)', null=True, storage=core.storage_backends.get_public_media_storage, upload_to='option_icons/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, help_text='Small icon/logo for the game (recommended: 64x64 or 128x128)', null=True, storage=core.storage_backends.get_public_media_storage, upload_to='game_icons/'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(storage=core.storage_backends.get_public_media_storage, upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (recommended: 256x256)', null=True, storage=core.storage_backends.get_public_media_storage, upload_to='avatars/'),
        ),
    ]
