# Generated by Django 5.2.14 on 2026-09-02 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_public_media_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiredListing',
            fields=[
                ('listing_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('game_slug', models.CharField(blank=True, default='', max_length=200)),
                ('category_slug', models.CharField(blank=True, default='', help_text='Buyer-facing URL slug of the category page it sat on.', max_length=200)),
                ('category_kind', models.CharField(blank=True, default='', help_text='The base category slug (keys, gift-cards, ...) — picks the section page when nothing closer is left.', max_length=200)),
                ('option_id', models.PositiveIntegerField(blank=True, null=True)),
                ('filter_values', models.JSONField(blank=True, default=dict)),
                ('heir_path', models.CharField(blank=True, default='', help_text="Where the old URL goes, e.g. /games/steam/gift-cards. Blank = worked out live: an active twin, else the category page, else the game's busiest page, else the section page.", max_length=300)),
                ('reason', models.CharField(choices=[('game_gone', 'Game gone from the supplier'), ('region_gone', 'Region no longer sold'), ('discontinued', 'Edition or pack discontinued'), ('hand_retired', 'Retired by hand'), ('superseded', 'Replaced by a renamed listing'), ('deleted', 'Deleted'), ('catalog_retired', 'Catalogue retirement')], default='deleted', max_length=20)),
                ('listing_created_at', models.DateTimeField(blank=True, null=True)),
                ('active_until', models.DateTimeField(blank=True, help_text='When it stopped being buyable. A listing that was buyable for under a day was never indexed and answers 404 instead of a redirect.', null=True)),
                ('retired_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Retired listing',
                'verbose_name_plural': 'Retired listings',
                'ordering': ['-retired_at'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='retire_reason',
            field=models.CharField(blank=True, choices=[('', 'Paused - may come back'), ('game_gone', 'Game gone from the supplier'), ('region_gone', 'Region no longer sold'), ('discontinued', 'Edition or pack discontinued'), ('hand_retired', 'Retired by hand'), ('superseded', 'Replaced by a renamed listing')], default='', help_text='Why an inactive listing is off. Blank = paused (shown as out of stock for up to 30 days, may come back). Any other value = gone for good: the page redirects to its heir right away.', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='unavailable_since',
            field=models.DateTimeField(blank=True, help_text='When the listing last stopped being buyable. Starts the out-of-stock clock: the page keeps serving for 30 days, then redirects to the nearest live page. Cleared automatically when the listing goes active again.', null=True),
        ),
    ]
