# Generated by Django 5.2.14 on 2026-09-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_listing_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRegionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.SlugField(help_text='Value of an option on this page\'s Region filter (e.g. "usa", "united-kingdom"). Becomes the last URL segment.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('seo_title', models.CharField(blank=True, default='', help_text='Search/browser title WITHOUT the "| GamesBazaar" suffix. May carry "from PKR {from_price}" — filled with the cheapest active listing in this region. Blank = "<Game> <Category> <Region> in Pakistan from PKR ...".', max_length=120)),
                ('seo_description', models.CharField(blank=True, default='', max_length=300)),
                ('seo_body', models.TextField(blank=True, default='', help_text='Visible SEO text below the listings, same conventions as the category page (blank line = paragraph, "## " heading, "### " FAQ question).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_pages', to='core.gamecategory')),
            ],
            options={
                'verbose_name': 'Category Region Page',
                'verbose_name_plural': 'Category Region Pages',
                'ordering': ['order', 'region'],
                'unique_together': {('game_category', 'region')},
            },
        ),
    ]
