# Generated by Django 5.2.14 on 2026-09-04 22:37

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_category_region_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoption',
            name='image',
            field=models.ImageField(blank=True, help_text='Product picture (3:2). Generated by generate_option_images; upload one here to override it.', null=True, storage=core.storage_backends.get_public_media_storage, upload_to='option_images/'),
        ),
    ]
