# Generated by Django 5.2.14 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    """Choices-only change: FazerFulfillmentTask gains the 'refunded' status
    (supplier refunded us → order cancelled, buyer refunded automatically).
    No schema change on the database."""

    dependencies = [
        ('core', '0081_category_region_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazerfulfillmenttask',
            name='status',
            field=models.CharField(
                choices=[
                    ('queued', 'Queued'),
                    ('placing', 'Placing'),
                    ('processing', 'Processing'),
                    ('delivered', 'Delivered'),
                    ('manual', 'Manual'),
                    ('attention', 'Needs Attention'),
                    ('refunded', 'Refunded'),
                ],
                default='queued',
                max_length=12,
            ),
        ),
    ]
