# Generated by Django 5.2.14 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    """Rental expiry reminders: two nullable stamps on Order so the hourly
    send_rental_expiry_emails timer never sends the same reminder twice."""

    dependencies = [
        ('core', '0082_fazer_task_refunded_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_expiry_email_72h_sent_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Rentals only: when the "ends in 3 days" reminder was queued '
                          '(send_rental_expiry_emails timer). Stays empty if the rental '
                          'was already inside its last 24 hours when first seen.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_expiry_email_24h_sent_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Rentals only: when the "ends in 24 hours" reminder was queued.',
                null=True,
            ),
        ),
    ]
