# Generated by Django 5.2.14 on 2026-09-20 16:44

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Withdrawals: drop the PKR 500 minimum to PKR 1 so a buyer can take any
    refunded amount out of their wallet."""

    dependencies = [
        ('core', '0083_order_rental_expiry_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='withdrawrequest',
            name='withdraw_amount_min_500',
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('1.00'))), name='withdraw_amount_min_1'),
        ),
    ]
